#!/bin/bash
#SBATCH -J b1024
#SBATCH -p rush
#SBATCH --nodelist=rush-compute01
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=2
#SBATCH --ntasks 1
#SBATCH --mem 12G

source /home/jtc257/.bashrc
source /home/jtc257/scripts/env.sh

hmmenv
cd /home/jtc257/python/hmm-lm

python main.py  --lr 0.001 --column_dropout 1 --transition_dropout 0 --dropout_type none     --model blhmm --bsz 256 --num_classes 1024 --emb_dim 256     --hidden_dim 256 --dataset ptb --iterator bucket
